modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="steve"
version="1.0.5"
displayName="Steve AI Mod"
description='''
AI-controlled Steve entities that can follow natural language commands,
mine resources, build structures, and behave like real players using LLMs.
'''
authors="LeaderOnePro"
displayURL="https://github.com/LeaderOnePro/Steve"
# Forked from https://github.com/YuvDwi/Steve

[[dependencies.steve]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.steve]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
